version: '3.8'

services:
  db:
    expose:
      - 3306
    image: arm64v8/mysql
    volumes: 
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: 1234
    networks:
      - wp

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=password
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=300M
    depends_on:
      - db
    networks:
      - wp

  wordpress:
    ports:
      - "${PORT:-8000}:80"
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_TABLE_PREFIX: da_
    networks:
      - wp
networks:
  wp:
volumes:
  db_data:
  wp_data: