version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean:latest
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:
      - JENKINS_HOME=/var/jenkins_home
    networks:
      - jenkins-net

networks:
  jenkins-net:

volumes:
  jenkins-data:

